Repository 2001-one-flew-over-the-cuckoo/grace-shopper, pull requests merged in 2020-03, with the labels that each got.

#29 Products
  client/app.js
  client/components/AllProducts.js
  client/components/SingleProduct.js
  client/routes.js
  client/store/index.js
  client/store/products.js
  client/store/singleProduct.js
  package-lock.json
  package.json
  public/style.css
  server/api/products.js
Labels: customer/visitor

#30 added user model and user/admin view components
  client/app.js
  client/components/admin-home.js
  client/components/index.js
  client/components/navbar.js
  client/components/user-home.js
  client/components/user-home.spec.js
  client/routes.js
  client/store/admin.js
  client/store/index.js
  package-lock.json
  package.json
  script/seed.js
  server/api/users.js
  server/db/models/user.js
Labels: admin, logged-in customer

#34 Users
  public/index.html
  server/api/users.js
  server/auth/index.js
  server/db/models/user.js
  server/db/models/user.spec.js
  server/index.js
Labels: admin, customer/visitor, engineer

#33 Products
  client/components/cart.js
  client/components/navbar.js
  client/components/user-home.js
  script/seed.js
  server/api/users.js
  server/auth/index.js
  server/db/models/cart.js
  server/db/models/index.js
  server/db/models/product.js
  server/db/models/product.spec.js
Labels: customer/visitor, enhancement, logged-in customer

#41 chore: update package.json
  package-lock.json
  package.json
Labels: dependencies

#43 Updates
  client/components/admin-home.js
  package-lock.json
  package.json
Labels: dependencies

#50 Cart session fix
  client/components/AllProducts.js
  client/components/SingleProduct.js
  client/components/cart.js
  client/components/checkout.js
  client/components/index.js
  client/routes.js
  client/store/cart.js
  client/store/user.js
  server/api/orders.js
  server/auth/index.js
  server/db/models/index.js
Labels: customer/visitor, enhancement, logged-in customer

#57 Cart quantity
  client/components/SingleProduct.js
  client/components/cart.js
  client/store/user.js
  server/api/cart.js
Labels: enhancement

#58 Cart quantity
  client/components/SingleProduct.js
  client/components/cart.js
  client/components/checkout.js
  package-lock.json
  package.json
Labels: bug, enhancement
